### ISSUE TITLE
你没有把eww配置放上去吗，佬

### ISSUE THREAD

**Issue by newbie163** [Cyberczy/dotfiles#1]

**Comment by Cyberczy** [comment]
eww我已经好久不用啦，原来就是时间那个nerd font，是一个eww的面板，但是开机第一次点会很慢我就弃用了。

**Comment by newbie163** [comment]
今天刚把hyprland滚挂，找不到原因，回x11了😖

**Comment by Cyberczy** [comment]
> 今天刚把hyprland滚挂，找不到原因，回x11了😖

你也在c佬群里啊

**Comment by newbie163** [comment]
哈哈哈，是啊
